version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "datapi3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-epb70ucm0dgn"
s3_prefix = "datapi3"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "APIName=\"datapi3\" APIKeyExpiration=\"1622111555\""
